// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbcH0nf7wp7kylFZYt7JwCj2_j0GolZ18',
    appId: '1:38040444521:web:e0b17c3119516c2aaa0cf8',
    messagingSenderId: '38040444521',
    projectId: 'app-firebase1-2025',
    authDomain: 'app-firebase1-2025.firebaseapp.com',
    storageBucket: 'app-firebase1-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnYcr15Zozzrau3La84KVWurXOqlOcI9s',
    appId: '1:38040444521:android:8371804c6fb9a1ecaa0cf8',
    messagingSenderId: '38040444521',
    projectId: 'app-firebase1-2025',
    storageBucket: 'app-firebase1-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgjHoI_u8_Lb1t-eSfs_50rk_aQVBdd5w',
    appId: '1:38040444521:ios:3bca5307da62b226aa0cf8',
    messagingSenderId: '38040444521',
    projectId: 'app-firebase1-2025',
    storageBucket: 'app-firebase1-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgjHoI_u8_Lb1t-eSfs_50rk_aQVBdd5w',
    appId: '1:38040444521:ios:3bca5307da62b226aa0cf8',
    messagingSenderId: '38040444521',
    projectId: 'app-firebase1-2025',
    storageBucket: 'app-firebase1-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbcH0nf7wp7kylFZYt7JwCj2_j0GolZ18',
    appId: '1:38040444521:web:a4d3f23ff0dc4ca9aa0cf8',
    messagingSenderId: '38040444521',
    projectId: 'app-firebase1-2025',
    authDomain: 'app-firebase1-2025.firebaseapp.com',
    storageBucket: 'app-firebase1-2025.firebasestorage.app',
  );
}
